language: java
jdk:
- oraclejdk8
sudo: false
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn package
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: philippe.damen@ordina.be
  password:
    secure: "MZlmr7rsLNAMXglvRmiWwvzkQavQaVqN6Mj/DoKc8w/DQBRZWo5kGWQF5IyuaX13Ph/dRJ8QVXL2iOQub8IqGfX7c0fDczRvApLSCoRyd88ea5zmqsjayxN85ICFC29ixqIUdokootVCh0jVhRfyGjOoewCQnohk1mM5MJI8gR
            aLJZ9BDXu/jisEzDqHvIjqeNtQfUYNvdflLz1NgGNMP+45bTPc5q1iAjsmgS8UJryR9hbmgyYy2v504fLze/RDRIVcpFFMAHPqErdG7hdJK2u/s1ZVjxiL89nu8ooBkpr3UgtUelbMoaf65fttJBUzsm75+eCJJAROSIyJUiJffzqO1NEvoY5
            Hu1er/erL8NhXJ0JZXzFKshbvy1GkPankhy3Y+BwtwTnOWfjbC9xn/3LHNIlOdFFcl3lHG00Wno+T3tYzsgnHis7nB1bYJHehljqSh6mLpvEDdgmgB5ygJQxPNm7hCXeh91qF8c56d2gBjoDmhW0DhccNDRwipP4R8xT2M5GGIwQ0C4I9hW9T
            M+6xG1YnFG3WItgipWjzVoQ/25MQitRPfywz+AeaO1PfZb9ArMHV1Aj6cCp/1qVcLgVTfIla5I0dDW0zQzMDlxsuaHVyP5Dpy6omI0l1X3gLAEKUbAvAcXZoqHtAed7LpzTkEftrmMR1GujRV3oU/2w="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/notification-service
    branch: master
after_deploy:
- mvn clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: DWbChbA0GKnvD1mbsaq3NDV0S8LpYkk3mfvQmwgNVT/K2GVbXS+Q2WV7RzHZft6PvFdKjYg49nH/6OhT+gmHvK7tdtUak9Zi7qjN9vmfb/QRMg0ln4pBSUGLwHuJyxlaffT3htYHdZnUYFaOqNG1NEyP+DD957FJobESPs765xFNThVLwMEyTAWT+ll9AV9HMn8QXZ9B0UrgM7XgC9L717e3MJhRFSFWBpDuQBto4qBA8uzvV4kqJEce5LJkGGG6lbXnQB4xF2SU9aEBMveUoxaXfHbgqVXYWQSNE1XsYb9aAkmQWPiNevfA7F71hIAHqmUvuJ3LMwDkotoGwluk4UM3CnjwU6olvYz8dsh92bbMwG+vIxln3a5nOWamDIZNhnPKIr9km4mAfMEk5ikqOgKr8wpGpm19vAxXvmrOjO38ZC7bOV8EXctWRzalXd8ZZseGfiVeJHgMA/LnYAr3LV+5svZqNouJLP62bGlePNr0fC7m19WGjmyB82WU+G+ntvXQSFXdIt1BG/u7roUYQaRxmYG/r2pCNAsP75tXb27pwUdcc3KMjzOFJ8YXOrwYx3zrk/yLZP8F66FXrkYKZq7qwmjqqI986R4dSC18NQvy7tzYPKafbltLb6TEqC4obu183EOyUNwGGemS+YobOekhaLUDyLq9fe6UsCMUEkM=
  email: false