server:
  port: ${PORT:1199}
spring:
  jackson:
    serialization:
      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: false
  data:
    rest:
      basePath: /api
      defaultMediaType: application/hal+json
      returnBodyOnUpdate: false
      returnBodyOnCreate: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    be.ordina: 'DEBUG'
    org.hibernate: 'ERROR'
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  https://eureka-ordineo.cfapps.io/eureka/ #http://localhost:8761/eureka/
  instance:
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false
ribbon:
  IsSecure: true
---
logging:
  level:
    org.springframework.security: INFO
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true